remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Membangun Website Dengan Lume dan MDX
description: \
  Membangun website berisi dokumentasi atau komersial menggunakan Lume dalam format MDX 
  dan Deno

